### ISSUE TITLE
Missing BigInteger export

### ISSUE THREAD

**Issue by 0ndorio** [keybase/kbpgp#114]
Could you please add the bn.iced exports to the library api? I know that you published a custom BigInteger module but it would be nice to have direct access to the real internal used version of BigInt and the related convenience methods.

Or is there any specific reason not to add this stuff to kbpgp or kbpgp-bn?

**Comment by maxtaco** [comment]
No real reason.  I can look at a PR if you send one!

**Comment by 0ndorio** [comment]
A short and simple solution is PR #115 which adds the custom stuff directly to the kbpgp exports.
