### ISSUE TITLE
test fail with pgp-utils version 0.0.32; 0.0.31 works fine

### ISSUE THREAD

**Issue by zapu** [keybase/kbpgp#133]
From what I understand, behavior of pgp-utils was changed in 0.0.31, and we had to fix tests in https://github.com/keybase/kbpgp/commit/76b7fcac3ab44703c1138815fe1ae359b29ca457

but it looks like they reverted the behavior in 0.0.32

```
~/pgp/kbpgp » cat node_modules/pgp-utils/package.json | grep version | grep 0
  "version": "0.0.31"
~/pgp/kbpgp » make test
...
Tests: 240/240 passed
~/pgp/kbpgp » rm -rf node_modules/pgp-utils
~/pgp/kbpgp » npm install pgp-utils@0.0.32
kbpgp@2.0.62 /home/zapu/pgp/kbpgp
└── pgp-utils@0.0.32 
~/pgp/kbpgp » cat node_modules/pgp-utils/package.json | grep version | grep 0
  "version": "0.0.32"
~/pgp/kbpgp » make test
- Assertion failed: control characters not allowed in armor
In reading /home/zapu/pgp/kbpgp/test/files/openpgp_js_cure53_audit.iced: TypeError: Cannot read property 'message' of null
TypeError: Cannot read property 'message' of null
...
✖ Failure due to test configuration issues
Tests: 239/240 passed
```

(sorry for ghetto grep version checking)

@maxtaco Refreshing the buildbot would probably expose this bug. The last "successful" job https://travis-ci.org/keybase/kbpgp/jobs/185556861 used 0.0.31, if it fails with 0.0.32 it would confirm this issue.

**Comment by zapu** [comment]
Oh, I didn't notice that pgp-utils is a "first party" package as well... pinging @oconnor663 then (sorry if for no good reason)

**Comment by maxtaco** [comment]
you're right, we forgot to back and change this!  we'll get it done
shortly...

**Comment by oconnor663** [comment]
Ah yep, my mistake. Fix PR is up.
