### ISSUE TITLE
Webpack dependency warning

### ISSUE THREAD

**Issue by AntonioJuliano** [keybase/kbpgp#157]
I'm getting the following warning while compiling my app using kbpgp with webpack:

```Warning in ./~/bn/lib/wrap.js
Critical dependencies:
6:11-30 the request of a dependency is an expression
 @ ./~/bn/lib/wrap.js 6:11-30

Warning in ./~/keybase-nacl/lib/main.js
Critical dependencies:
16:13-32 the request of a dependency is an expression
 @ ./~/keybase-nacl/lib/main.js 16:13-32
```

Using npm and versions:
kbpgp: 2.0.72, webpack: 3.0.0

The warning disappears when I stop including kbpgp, so that seems to be the issue.

I think this is an issue with kbpgp itself, but please let me know if it's an issue with webpack or my setup instead

**Comment by stabback** [comment]
If you're experiencing this and would like to silence the warnings, extend your webpack config with this line:

```js
config.module.exprContextCritical = false
```

Note this doesn't resolve the root issue.

**Comment by maxtaco** [comment]
Should be fixed, reopen if not!
