### ISSUE TITLE
"RFC4880 Implementation in IcedCoffeeScript" - WAT?

### ISSUE THREAD

**Issue by pfalcon** [keybase/kbpgp#169]
Would you be so kind to let people discover your wonderful project, and you get your deserved fame, by providing an adequate description for the github project? You don't think that everyone knows what RFC4880 is, and that everyone will rush to google it up, do you? Most people would just pass by to more well-lit places.

Suggested description:

> RFC4880 (OpenPGP) Implementation in IcedCoffeeScript

Thanks!

**Comment by maxtaco** [comment]
good idea, thanks!

**Comment by pfalcon** [comment]
Thanks!
