### ISSUE TITLE
How to verify

### ISSUE THREAD

**Issue by TheChiefMeat** [keybase/kbpgp#171]
I'm having a little trouble at the last hurdle, I can't seem to verify a signed message.

I have decryption working fine, I'm importing the private and public keys like so using a html5 form (assume these keys are from two different people):

```
var decryptionPrivateKey = $("#decryption-private-key");
var decryptionPublicKey = $("#decryption-public-key");
```

But I don't understand how I use those two variables in the key manager. I understand that the layout is as follows:

```
var ring = new kbpgp.keyring.KeyRing;
var kms = [decryptee, signee];
    for (var i in kms)
        ring.add_key_manager(kms[i]);
```
What do I put in the decryptee and signee parts? I've tried adding it as

 `decryptionPrivateKey.val(), decryptionPublicKey.val()`

but that doesn't seem to work, it always throws this error regardless of what I do.

`km.export_pgp_keys_to_keyring is not a function`

**Comment by Owlincfr** [comment]
I think that _decryptee_ and _signee_ must be KeyManager instance.

Try to place this code after loading keys (https://keybase.io/kbpgp/docs/loading_a_key)

Do so :
```javascript
var decryptionPrivateKey = $("#decryption-private-key");
var decryptionPublicKey = $("#decryption-public-key");
var decryptionPrivateKey_passphrase = $("#decryption-private-key-passphrase");

kbpgp.KeyManager.import_from_armored_pgp({
  armored: decryptionPublicKey
}, function(err, signee) {
  if (!err) {
    // signee is loaded
    // Now we want to load decryptee

		kbpgp.KeyManager.import_from_armored_pgp({
			armored: decryptionPrivateKey
		}, function(err, decryptee) {
			if (!err) {
				if (decryptee.is_pgp_locked()) {
					decryptee.unlock_pgp({
						passphrase: decryptionPrivateKey_passphrase
					}, function(err) {
						if (!err) {
							//console.log("Loaded private key with passphrase");
						}
					});
				} else {
					//console.log("Loaded private key w/o passphrase");
				}
			}
			
			// Here we have two KeyManager instances : signee and decryptee
			// We can add them to the KeyRing
			
			var ring = new kbpgp.keyring.KeyRing();
			var kms = [ signee, decryptee ];
			for (var i in kms) {
				ring.add_key_manager(kms[i]);
			}
		});
  }
});
```

Can you test that and tell me if it works ?

**Comment by TheChiefMeat** [comment]
Hey thanks for helping, but that comment was quite a while ago now and I've already figured it all out xD Thank you anyway, hopefully someone else will find it useful :)
