### ISSUE TITLE
keybase-ecurve code and license

### ISSUE THREAD

**Issue by OliverCole** [keybase/kbpgp#189]
`kbpgp` depends on [keybase-ecurve](https://www.npmjs.com/package/keybase-ecurve), however the code for that doesn't appear to be released? The NPM page links to the code for [ecurve](https://github.com/cryptocoinjs/ecurve), which the [developer says](https://github.com/cryptocoinjs/ecurve/issues/41) is the original, and `keybase-ecurve` is a fork.

This is a problem because [keybase-ecurve](https://www.npmjs.com/package/keybase-ecurve) doesn't state a software license, so I can't use it at all.

Can you publish `keybase-ecurve` with a license, or ideally publish your fork, with a license?

**Comment by maxtaco** [comment]
Should be fixed in 2.1.4, LMK if not.
