### ISSUE TITLE
https://keybase.io/kbpgp is showing the original 1.0.0 release

### ISSUE THREAD

**Issue by gabriel** [keybase/kbpgp#46]
https://keybase.io/kbpgp is showing the older 1.0.0 release

**Comment by yousefamar** [comment]
Posting here to avoid duplicate issue. Currently https://keybase.io/kbpgp links to a zip on 2.0.8 which is an older version, and the rel directory with the minified builds hasn't had a new build in quite some time.

**Comment by maxtaco** [comment]
Updated, thanks
