### ISSUE TITLE
Lack of docs on importing a private key in P3SKB format (obtained from Keybase API)

### ISSUE THREAD

**Issue by vovayartsev** [keybase/kbpgp#68]
Hi,

It's not quite clear from https://keybase.io/kbpgp/docs/loading_a_key how to load a private key obtained through Keybase API.  

I'm doing the following operations:

1. Login into Keybase (https://keybase.io/docs/api/1.0/call/login)
2. Get a key manager containing a private key from login response in `me.private_keys.primary.bundle` field
3. Sign a message using that key manager

The [documented workflow](https://keybase.io/kbpgp/docs/loading_a_key) didn't work for me, because the key returned from Keybase is in P3SKB format. 

PS: I tried a non-documented function `import_from_p3skb`, but this resulted in a key manager which can't sign anything. Also the key imported doesn't seem to be locked, which is strange.
```javascript
kbpgp.KeyManager.import_from_p3skb({raw: me.private_keys.primary.bundle}, function (err, key) {
  // err => null
  // key => KeyManager {primary: Primary, subkeys: Array[1], userids: Array[1], armored_pgp_public: "", armored_pgp_private: undefined…}
  // key.is_pgp_locked() => false     - WHY???
  kbpgp.box({msg: "Hello", sign_with: key}, function (err, x, y) {
    // err => Error: cannot sign with the given KeyManage
  }
})
```

Am I on a right way? Or should I try [converting P3SKB -> Standard PGP blocks](https://gist.github.com/maxtaco/b5c0983ba96b8dc88c5f) instead?

**Comment by vovayartsev** [comment]
Ups... It duplicates https://github.com/keybase/keybase-issues/issues/688. Sorry.

**Comment by mtotheikle** [comment]
@vovayartsev do you mind elaborating on what you did to fix your issue? I'm not seeing what's detailed in referenced issue that should stop this from working. I'm hoping to decrypt the private key so that I can encrypt data on a custom site with the key from Keybase

Thanks!
