### ISSUE TITLE
Proper way of locking a key back

### ISSUE THREAD

**Issue by luisivan** [keybase/kbpgp#86]
Hey,

What would be the proper way to do the inverse of `unlock_pgp`? I want to have the keys locked most of the time and just unlock them when needed and then lock them back

Thanks and congrats on building such a great lib

**Comment by maxtaco** [comment]
Try:

```coffeescript
km = # my key manager
km.export_pgp_private { passphrase : "foobar" } , (err, armored) ->
   console.log armored
```

**Comment by luisivan** [comment]
Thanks for the quick reply @maxtaco 
Yeah I'm doing that right now, fetching the passphrase-encrypted privkey in armored text, then loading and unlocking it. The thing is that I'd love to lock it back (so I need to unlock it again for each sign/decrypt operation) without having to destroy the KeyManager instance and creating another one.

**Comment by maxtaco** [comment]
I see.  We don't have great support for something like that, sorry to say.  But just to push back a little bit, how will you lock the secret keys and who are you protecting against?  If you want to protect against an attacker in-process, then they can grab whatever key you're using the lock the secret keys too.

**Comment by luisivan** [comment]
That's true.
So, for example, what do you do in Keybase? Once I sign/decrypt something with my passphrase then you keep the keypair unlocked?

**Comment by maxtaco** [comment]
We wind up throwing away the unlocked copy every time, but almost as much
out of laziness as of out of concern for security.

**Comment by luisivan** [comment]
@maxtaco good to know! Thanks. Keep up the great work, Iced & Keybase lover here :+1:

**Comment by maxtaco** [comment]
Thanks Luis!
