### ISSUE TITLE
Make `export_pgp_public` nonblocking, memoized

### ISSUE THREAD

**Issue by Sidnicious** [keybase/kbpgp#88]
This is an API change, but it doesn't need to take a callback and changing it will make some Keybase changes easier. Let's also make it cache its result in `@armored_pgp_public`.

**Comment by maxtaco** [comment]
Thought a little bit about this, I would advise against.  You'd have to change the code in way too many places, and we've already published the API as is.  Is there a way to get the same result without interfering with code that's already in the wild?

**Comment by maxtaco** [comment]
(In other words, I don't think the upside is worth all the bugs this change might introduce.)

**Comment by maxtaco** [comment]
I whipped this together, we can make this change backwards compatible with the existing API.

**Comment by Sidnicious** [comment]
Fixed in 90c9ec99e4100643dd55a3aca6243bb4df011c2a.
