### ISSUE TITLE
Support Curve25519 DH

### ISSUE THREAD

**Issue by maxtaco** [keybase/kbpgp#92]
As mentioned here keybase/keybase-issues#1738

**Comment by xkxx** [comment]
What kind of work is required for this (surely it's not simply inputting the curve parameters in curves.iced)? If I'm interested in this, how would I be able to help?

**Comment by maxtaco** [comment]
Thanks xkxx! There are two implementations we need --- one for kbpgp and
another for go-crypto/Openpgp.  My guess is that curve 25519 is different
enough from the nist curves that there might be some extra differences. For
instance Montgomery versus weierstrass form. However we already do have
curve25519 implementations in both libraries as I am sure you've seen.
Thanks!!!

**Comment by xkxx** [comment]
OK I noticed that kbpgp currently relies on keybase-nacl, which does implement curve2519 ecdh. I'm wondering if we can make use of that here...

**Comment by maxtaco** [comment]
Yes definitely
